export default [
  {
    href: "/public/favicon/apple-icon-57x57.png",
    type: "image/png",
    rel: "apple-touch-icon",
    sizes: "57x57",
  },
  {
    href: "/public/favicon/apple-icon-60x60.png",
    type: "image/png",
    rel: "apple-touch-icon",
    sizes: "60x60",
  },
  {
    href: "/public/favicon/apple-icon-72x72.png",
    type: "image/png",
    rel: "apple-touch-icon",
    sizes: "72x72",
  },
  {
    href: "/public/favicon/apple-icon-76x76.png",
    type: "image/png",
    rel: "apple-touch-icon",
    sizes: "76x76",
  },
  {
    href: "/public/favicon/apple-icon-114x114.png",
    type: "image/png",
    rel: "apple-touch-icon",
    sizes: "114x114",
  },
  {
    href: "/public/favicon/apple-icon-120x120.png",
    type: "image/png",
    rel: "apple-touch-icon",
    sizes: "120x120",
  },
  {
    href: "/public/favicon/apple-icon-144x144.png",
    type: "image/png",
    rel: "apple-touch-icon",
    sizes: "144x144",
  },
  {
    href: "/public/favicon/apple-icon-152x152.png",
    type: "image/png",
    rel: "apple-touch-icon",
    sizes: "152x152",
  },
  {
    href: "/public/favicon/apple-icon-180x180.png",
    type: "image/png",
    rel: "apple-touch-icon",
    sizes: "180x180",
  },
  {
    href: "/public/favicon/android-icon-36x36.png",
    type: "image/png",
    rel: "icon",
    sizes: "36x36",
  },
  {
    href: "/public/favicon/android-icon-48x48.png",
    type: "image/png",
    rel: "icon",
    sizes: "48x48",
  },
  {
    href: "/public/favicon/android-icon-72x72.png",
    type: "image/png",
    rel: "icon",
    sizes: "72x72",
  },
  {
    href: "/public/favicon/android-icon-96x96.png",
    type: "image/png",
    rel: "icon",
    sizes: "96x96",
  },
  {
    href: "/public/favicon/android-icon-144x144.png",
    type: "image/png",
    rel: "icon",
    sizes: "144x144",
  },
  {
    href: "/public/favicon/android-icon-192x192.png",
    type: "image/png",
    rel: "icon",
    sizes: "192x192",
  },
  {
    href: "/public/favicon/favicon-32x32.png",
    type: "image/png",
    rel: "icon",
    sizes: "32x32",
  },
  {
    href: "/public/favicon/favicon-96x96.png",
    type: "image/png",
    rel: "icon",
    sizes: "96x96",
  },
  {
    href: "/public/favicon/favicon-16x16.png",
    type: "image/png",
    rel: "icon",
    sizes: "16x16",
  },
  {
    href: "/public/favicon/ms-icon-70x70.png",
    type: "image/png",
    rel: "msapplication-TileImage",
    sizes: "70x70",
  },
  {
    href: "/public/favicon/ms-icon-150x150.png",
    type: "image/png",
    rel: "msapplication-TileImage",
    sizes: "150x150",
  },
  {
    href: "/public/favicon/ms-icon-310x310.png",
    type: "image/png",
    rel: "msapplication-TileImage",
    sizes: "310x310",
  },
  {
    href: "/public/favicon/ms-icon-144x144.png",
    type: "image/png",
    rel: "msapplication-TileImage",
    sizes: "144x144",
  },
];
